blank_issues_enabled: false
contact_links:
  - name: Read the Docs
    url: https://manual.emudeck.com/
    about: Do not use GitHub Issues for support. Read the docs or join the EmuDeck Discord.
  - name: EmuDeck Discord
    url: https://discord.gg/b9F7GpXtFP
    about: Do not use GitHub Issues for support. Please ask and answer questions in the Discord.